import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local"
import CustomCursor from "@/components/CustomCursor";

import Navbar from "@/components/Navbar";

const coolvetica = localfont({
  src: [
    {
      path: "../public/fonts/Coolvetica Rg.otf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-coolvetica"
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomCursor />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
